# Generated by Django 4.1.3 on 2022-11-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_habit_dailyrecord"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="dailyrecord",
            constraint=models.UniqueConstraint(
                fields=("date", "habit"), name="unique_daily_record_for_habit"
            ),
        ),
    ]
